<?php
require_once '../sass/db_config.php';
session_start();
$admin_id = $_SESSION['admin_id'] ?? 0;

$student_id = intval($_GET['student_id'] ?? 0);
if (!$student_id) {
    echo "<div class='alert alert-danger'>Invalid Student ID</div>";
    exit;
}

// Fetch student
$student = $conn->query("SELECT * FROM students WHERE id = $student_id AND school_id = $admin_id")->fetch_assoc();
if (!$student) {
    echo "<div class='alert alert-danger'>Student not found.</div>";
    exit;
}

// Fetch school
$school = $conn->query("SELECT * FROM schools WHERE id = $admin_id")->fetch_assoc();

// Fee types
$feeTypes = [];
$feeTypeQ = $conn->query("SELECT id, fee_name FROM fee_types WHERE school_id = $admin_id");
while ($ft = $feeTypeQ->fetch_assoc()) {
    $feeTypes[$ft['id']] = $ft['fee_name'];
}

// Class fee structure
$feeRow = array_fill_keys(array_keys($feeTypes), 0);
$class = $student['class_grade'];
$classFees = $conn->query("SELECT * FROM class_fee_types WHERE school_id = $admin_id AND class_grade = '{$class}'");
while ($cf = $classFees->fetch_assoc()) {
    $feeRow[$cf['fee_type_id']] = $cf['rate'];
}

// Student-specific override
$studentFees = $conn->query("SELECT * FROM student_fee_plans WHERE school_id = $admin_id AND student_id = $student_id");
while ($sf = $studentFees->fetch_assoc()) {
    $feeRow[$sf['fee_component']] = $sf['base_amount'];
}

// Scholarship
$scholarship = $conn->query("SELECT * FROM scholarships WHERE school_id = $admin_id AND student_id = $student_id AND status = 1")->fetch_assoc();
$scholarship_amount = 0;
$studentTotal = array_sum($feeRow);

if ($scholarship) {
    if ($scholarship['type'] === 'percentage') {
        $scholarship_amount = $studentTotal * ($scholarship['amount'] / 100);
    } else {
        $scholarship_amount = $scholarship['amount'];
    }
}

$payable = $studentTotal - $scholarship_amount;

// Fee Slip Output
?>

<div class="text-center mb-4">
    <img src="../uploads/<?= $school['logo'] ?>" class="logo mb-2"><br>
    <strong><?= $school['school_name'] ?></strong><br>
    <?= $school['address'] ?><br>
    Phone: <?= $school['school_phone'] ?> | Email: <?= $school['school_email'] ?>
</div>

<hr>

<div class="row mb-3">
    <div class="col-md-6">
        <strong>Student Name:</strong> <?= $student['full_name'] ?><br>
        <strong>Class:</strong> <?= $student['class_grade'] ?> - <?= $student['section'] ?><br>
        <strong>Roll No:</strong> <?= $student['roll_number'] ?><br>
    </div>
    <div class="col-md-6 text-end">
        <strong>Slip Date:</strong> <?= date('Y-m-d') ?><br>
        <strong>Generated By:</strong> <?= $school['admin_contact_person'] ?><br>
    </div>
</div>

<table class="table table-bordered">
    <thead class="table-primary">
        <tr>
            <th>Fee Component</th>
            <th class="text-end">Amount (PKR)</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($feeRow as $fid => $amount): ?>
        <tr>
            <td><?= $feeTypes[$fid] ?></td>
            <td class="text-end"><?= number_format($amount) ?></td>
        </tr>
        <?php endforeach; ?>
        <tr class="table-info">
            <th>Total</th>
            <th class="text-end"><?= number_format($studentTotal) ?></th>
        </tr>
        <?php if ($scholarship): ?>
        <tr class="table-warning">
            <th>Scholarship (<?= $scholarship['type'] ?> -
                <?= $scholarship['amount'] ?><?= $scholarship['type'] == 'percentage' ? '%' : ' PKR' ?>)</th>
            <th class="text-end">-<?= number_format($scholarship_amount) ?></th>
        </tr>
        <?php endif; ?>
        <tr class="table-success">
            <th>Payable Amount</th>
            <th class="text-end"><?= number_format($payable) ?></th>
        </tr>
    </tbody>
</table>

<div class="text-end mt-3">
    <em>Generated on <?= date('d M Y h:i A') ?></em>
</div>